site:
  name: Cigales.cloud
  site: 'https://cigales.cloud'
  base: '/'
  trailingSlash: false
  googleSiteVerificationId: xx-xxxx-xxxx
  contact:
    email: 'contact@cigales.cloud'
    phone: '+33 4 40 00 00 00'
    address: 'Cigales.cloud, 42 Green Valley Lane, Conservation City, Earth'
  social:
    github: 'github.com/cigales-cloud'
    twitter: '@cigales-cloud'
  products:
    sense: 'https://sense.cigales.cloud'
    status: 'https://status.cigales.cloud'

# Default SEO metadata
metadata:
  title:
    default: Cigales.cloud
    template: '%s — Cigales.cloud'
  description: "\U0001F680 Empowering Nature with Technology for a Sustainable Future."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Cigales.cloud
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@cigales-cloud'
    site: '@cigales-cloud'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
